<?php

namespace App\Support;

/**
 * TrainingCenterLessons — static HTML-center lesson library.
 * Rendered as normal website pages (Blade). All examples synthetic [TRAINING].
 * Structure per lesson: what / why / who / when / steps / example /
 * expected / mistakes / problems[] / next derived from order.
 */
class TrainingCenterLessons
{
    public static function categories(): array
    {
        return [
            'getting-started' => 'Getting Started',
            'customers' => 'Customer Management',
            'sales' => 'Sales',
            'delivery' => 'Service Delivery',
            'finance' => 'Finance',
            'knowledge' => 'Knowledge & AI',
            'security' => 'Security',
        ];
    }

    public static function all(): array
    {
        return [
            [
                'slug' => 'platform-overview', 'category' => 'getting-started', 'title' => 'Platform Overview',
                'summary' => 'What PerfectITSecurity does and how work flows from visitor to follow-up.',
                'what' => 'PerfectITSecurity provides IT support, cybersecurity, web development, software services, digital marketing, server management and consulting through one website that connects visitors, customers, staff work and company money.',
                'why' => 'Every action you take sits inside one lifecycle. Acting out of order (work before payment terms, orders before acceptance) breaks finance and delivery.',
                'who' => 'Every employee, on day one.',
                'when' => 'Before touching any record. Revisit whenever you are unsure what comes next.',
                'steps' => ['Visitor discovers the site (services page, contact form, referral, campaign)', 'Visitor becomes a lead or registered customer', 'A service request records the requirement', 'A quotation or proposal prices the work', 'The customer accepts; an order is created', 'Payment is recorded against the invoice', 'Work runs as a project with tasks', 'Quality review, final invoice, closure and follow-up'],
                'example' => '[TRAINING] Alex Morgan of NorthBridge Retail Ltd needs Managed IT Support (£1,500). The inquiry becomes a lead, then a request, a £1,500 quotation, an accepted order, staged payments, a delivery project, and finally a closed account with £0 due.',
                'expected' => 'You can place any task you receive inside the lifecycle and name what came before and what must come next.',
                'mistakes' => ['Starting work before the payment position is clear', 'Treating an inquiry as if it were an order'],
                'problems' => ['order-missing', 'project-not-created'],
            ],
            [
                'slug' => 'user-roles', 'category' => 'getting-started', 'title' => 'User Roles & Access',
                'summary' => 'Permissions matrix: what each role can access, own and do.',
                'what' => 'Access is enforced by the staff/customer boundary plus role checks: finance records need the finance tier, tickets need the support hierarchy, projects and tasks need the project hierarchy, and users, settings, audit logs, security and backups are admin-only. Trainers manage Academy content.',
                'why' => 'RBAC protects customer data and company money. Unauthorized attempts return 403 errors and are logged.',
                'who' => 'Everyone. Your sidebar only shows what your role may access.',
                'when' => 'Whenever you hit a permission error or need data outside your area — escalate instead of sharing accounts.',
                'steps' => ['Identify the record type (finance, ticket, project, content)', 'Match it to the owning tier', 'If you lack access, escalate with a clear request', 'Never share logins to bypass access'],
                'example' => '[TRAINING] A support agent cannot open invoices. Instead of borrowing a finance login, they ask finance to confirm the payment state and post the verified answer to the ticket.',
                'expected' => 'Fewer 403 surprises, no shared accounts, clean audit trails.',
                'mistakes' => ['Sharing logins', 'Requesting customer data your role should not hold'],
                'problems' => ['cannot-access-task', 'page-not-loading'],
            ],
            [
                'slug' => 'daily-workflow', 'category' => 'getting-started', 'title' => 'Employee Daily Workflow',
                'summary' => 'Role-specific login-to-logout routine: triage, work, update, review, close.',
                'what' => 'A daily routine that keeps queues, SLAs and customers under control: login, dashboard, notifications, assigned tasks and tickets in SLA order, customer messages, prioritized work with notes, progress updates, review, verified closure, end-of-day sweep, logout.',
                'why' => 'Without a routine, urgent-but-quiet work (SLA clocks, due follow-ups) burns while visible-but-trivial work gets attention.',
                'who' => 'Every employee, adapted to role: sales works the pipeline oldest-first; support works SLA-deadline-first.',
                'when' => 'Every working day, first 15 minutes for triage and last 15 for the sweep.',
                'steps' => ['Login, check dashboard and notifications', 'Sort queue: SLA deadlines and due follow-ups first', 'Work with notes and evidence as you go', 'Post customer updates with next steps and dates', 'Submit for review; close only verified work', 'End-of-day sweep: nothing silent, overdue or ownerless'],
                'example' => '[TRAINING] A support morning: 1 overdue ticket (respond first), 2 tasks due today, 1 customer message awaiting a date. By 9:30 all have owners and next actions.',
                'expected' => 'Clean handoffs, met SLAs, and a queue you can defend at any moment.',
                'mistakes' => ['Working newest-first while SLA burns', 'Closing work without confirmation'],
                'problems' => ['ticket-not-assigned', 'sla-at-risk'],
            ],
            [
                'slug' => 'customer-journey', 'category' => 'customers', 'title' => 'Customer Journey Start to Finish',
                'summary' => 'The full lifecycle: visitor to inquiry, lead, customer, order, delivery, closure, follow-up.',
                'what' => 'The journey every customer takes: Visitor → Inquiry → Lead → Customer → Service Request → Quotation → Proposal → Approval → Order → Payment → Project → Tasks → Delivery → Progress Updates → Quality Review → Invoice → Final Payment → Finance Verification → Completion → Account Closure → Follow-up.',
                'why' => 'Skipped steps create orphans: unlinked projects, unverified payments, closed accounts with balances open.',
                'who' => 'Sales owns inquiry-to-order; delivery owns project-to-completion; finance owns money verification; everyone owns communication.',
                'when' => 'Use it to locate any piece of work and to check prerequisites before acting.',
                'steps' => ['Capture the inquiry with source and verbatim requirement', 'Create and qualify the lead', 'Record the service request with priority and owner', 'Price with quotation, package with proposal', 'Record acceptance, create and confirm the order', 'Verify payments against records', 'Deliver via project and tasks with updates', 'Quality-review, settle the invoice, verify £0 due, close, follow up'],
                'example' => '[TRAINING] Alex Morgan, NorthBridge Retail Ltd, Managed IT Support, £1,500: website inquiry → qualified lead → request → quotation → acceptance → order → £500 + £1,000 verified payments → project → tasks → updates → review → paid invoice → closure → follow-up call booked.',
                'expected' => 'One traceable chain from first click to follow-up, every link evidenced.',
                'mistakes' => ['Orders before acceptance', 'Delivery before payment position is clear', 'Closure with balances open'],
                'problems' => ['order-missing', 'payment-not-showing', 'balance-wrong'],
            ],
            [
                'slug' => 'crm', 'category' => 'customers', 'title' => 'CRM & Lead Management',
                'summary' => 'Lead lifecycle new → contacted → qualified → proposal → won/lost, dedupe and conversion.',
                'what' => 'The CRM (Admin → Leads, Sales Pipeline) tracks potential business. Leads carry source, value, priority, assignee, notes, activities and next follow-up date, and move new → contacted → qualified → proposal → won (convert) or lost with a reason.',
                'why' => 'The pipeline is the company forecast. Dirty CRM data means double-contacted customers and lost deals.',
                'who' => 'Sales staff own leads; anyone spotting a new inquiry must log it, not pocket it.',
                'when' => 'At first contact, at every touch, and at every status change.',
                'steps' => ['Search by name, email and company before creating — avoid duplicates', 'Create with source, estimated value, priority and assignee', 'Log every contact as an activity with a next follow-up date', 'Qualify on need, budget and authority', 'Convert only on acceptance; close lost with a reason'],
                'example' => '[TRAINING] NorthBridge Retail Ltd enters as a Website Inquiry (£1,500, sales owner). Two calls logged, qualified on the second, proposal sent, accepted, converted — one customer record, full history.',
                'expected' => 'No duplicates, no ownerless leads, every status change explained in history.',
                'mistakes' => ['Duplicate customers', 'Leads rotting in “new” with no next action', 'Converting before acceptance'],
                'problems' => ['duplicate-customer', 'lead-not-converting'],
            ],
            [
                'slug' => 'customer-communication', 'category' => 'customers', 'title' => 'Customer Communication',
                'summary' => 'Professional templates for started, progress, delay, completion, payment and follow-up moments.',
                'what' => 'Customer messages live in tickets and project channels so history is kept. Use fixed shapes: Work Started, Progress Update, Delay Notice (cause, impact, new date, owner — early), Completion, Payment Reminder (amount, due date, where to pay in /portal), Follow-up (value first, then the ask).',
                'why' => 'Written words are the service record. Vague or leaky messages create disputes and breach confidentiality.',
                'who' => 'Whoever owns the ticket, task or project at that moment.',
                'when' => 'At every state change the customer can feel: start, progress, delay, completion, money.',
                'steps' => ['Pick the template for the moment', 'Fill facts: stage, date, amount, link', 'Strip internal names, costs and security detail', 'Send via the ticket or project channel'],
                'example' => '[TRAINING] Progress: “Your project has progressed to the analysis stage. The assigned team is currently reviewing the collected information. Next update: tomorrow.” Completion: “The requested service is complete and deliverables are available in your customer portal.”',
                'expected' => 'Customers always know state, next step and date — without ever seeing internals.',
                'mistakes' => ['Promising dates you do not own', 'Pasting internal notes to customers'],
                'problems' => ['customer-update-not-visible', 'email-not-sent'],
            ],
            [
                'slug' => 'services', 'category' => 'sales', 'title' => 'Services Catalogue',
                'summary' => 'Matching customer requirements to services, scope and missing information.',
                'what' => 'Services (Admin → Services, public catalogue) define what the company sells: IT support lines, cybersecurity assessments, web development, digital marketing and more, with categories, descriptions and pricing.',
                'why' => 'A wrong service match poisons everything downstream: wrong price, wrong team, wrong delivery.',
                'who' => 'Sales matches and scopes; delivery validates feasibility before quotation.',
                'when' => 'During inquiry handling and service-request creation.',
                'steps' => ['Read the requirement in the customer’s own words', 'Match to the catalogue service and category', 'List what is missing and ask precisely for it', 'Confirm scope boundaries and exclusions early'],
                'example' => '[TRAINING] “Review our website for weaknesses plus a report” matches Website Security Assessment — scope: authorized assessment plus findings report; exclusion: remediation work and out-of-scope systems.',
                'expected' => 'A scoped, feasible requirement ready for quotation.',
                'mistakes' => ['Guessing scope instead of asking', 'Promising services not in the catalogue'],
                'problems' => ['missing-content', 'broken-link'],
            ],
            [
                'slug' => 'quotations', 'category' => 'sales', 'title' => 'Quotations',
                'summary' => 'Pricing line items, tax, validity, terms, revisions and acceptance.',
                'what' => 'A quotation (finance tier: Admin → Quotations) prices a defined scope: line items × quantity, discounts only with authorization, explicit tax treatment, total, validity period and terms. Revisions create new versions; sending and acceptance are timestamped.',
                'why' => 'The quotation is a financial commitment point. Sloppy quotes become disputes and revenue leakage.',
                'who' => 'Sales prepares; finance tier owns the totals; the customer accepts.',
                'when' => 'After scope is confirmed, before any order exists.',
                'steps' => ['Confirm scope, exclusions and timeline with the customer', 'Price line items; set tax explicitly; apply authorized discounts only', 'Set validity (e.g. 30 days) and terms; send and track status', 'Handle revisions as new versions', 'Record acceptance with timestamp before creating the order'],
                'example' => '[TRAINING] NorthBridge assessment £1,500: one line item, tax stated, 30-day validity, scope plus exclusions listed. Customer accepts on day 6 — acceptance logged, order unlocked.',
                'expected' => 'A versioned, accepted price the order can reference exactly.',
                'mistakes' => ['Unauthorized discounts', 'Missing exclusions', 'Orders created before acceptance'],
                'problems' => ['invoice-problem', 'order-status-wrong'],
            ],
            [
                'slug' => 'proposals', 'category' => 'sales', 'title' => 'Proposals & Contracts',
                'summary' => 'Packaging scope, approach and timeline; contracts and subscriptions for ongoing work.',
                'what' => 'Proposals (Admin → Proposals) wrap the quotation in approach, timeline and deliverables for approval. Contracts and subscriptions (finance tier) govern ongoing or recurring commitments with renewal terms.',
                'why' => 'Proposals win complex deals; contracts protect recurring revenue and set renewal expectations.',
                'who' => 'Sales drafts; delivery validates approach; finance tier owns contract records.',
                'when' => 'Proposals for multi-stage or high-value work; contracts before recurring billing starts.',
                'steps' => ['Draft scope, approach, milestones and timeline', 'Attach the priced quotation', 'Send for approval; revise as new versions', 'On acceptance, create the order; file contracts/subscriptions for recurring work'],
                'example' => '[TRAINING] A 3-service BrightWave proposal (£3,500) sequences IT support onboarding, security assessment, then maintenance — each with milestones the project later mirrors.',
                'expected' => 'Approved plan that delivery can execute without reinterpretation.',
                'mistakes' => ['Approach the team cannot deliver', 'Recurring work without a contract record'],
                'problems' => ['order-missing', 'invoice-problem'],
            ],
            [
                'slug' => 'orders', 'category' => 'sales', 'title' => 'Order Management',
                'summary' => 'Acceptance → order → review → payment check → confirmation → project trigger.',
                'what' => 'Orders (customers: /portal/orders; staff: work orders and order views) are accepted commitments. Flow: acceptance recorded → order created from the proposal → reviewed (price, scope, customer) → payment requirement checked with finance → confirmed on payment evidence → project creation triggered → customer notified.',
                'why' => 'The order is the handoff from sales to delivery. A bad handoff means delivery plans against fiction.',
                'who' => 'Sales creates and reviews; finance checks payment; project tier creates delivery.',
                'when' => 'Only after acceptance is timestamped — never on inquiry alone.',
                'steps' => ['Create the order from the accepted proposal only', 'Review pricing, scope and customer linkage', 'Confirm the payment requirement with finance', 'Confirm on payment evidence; trigger project creation', 'Notify the customer of confirmation and what happens next'],
                'example' => '[TRAINING] NorthBridge £1,500: accepted proposal → order → reviewed → £500 initial verified → confirmed → security-assessment project created and assigned.',
                'expected' => 'A confirmed order linked to its proposal, payment position and delivery project.',
                'mistakes' => ['Confirming with no payment position', 'Orders disconnected from proposals', 'Wrong customer linked'],
                'problems' => ['order-missing', 'order-status-wrong', 'project-not-created'],
            ],
            [
                'slug' => 'payments', 'category' => 'finance', 'title' => 'Payment Verification',
                'summary' => 'Customer payment path plus employee verification: records, partials, receipts, balances.',
                'what' => 'Customers pay from /portal against invoices or orders and receive confirmation plus receipts. Employees verify ONLY from platform records: payment status (unpaid, partially_paid, paid, overdue), amounts, transaction references, invoice state and remaining balance.',
                'why' => 'False payment statements destroy trust and corrupt accounts. Evidence is the only truth.',
                'who' => 'Customers pay; finance tier verifies and records; delivery checks status before proceeding.',
                'when' => 'At order confirmation, at every receipt, before delivery milestones, and before closure.',
                'steps' => ['Open the invoice or order; read total, amount_paid, amount_due', 'Match each payment record (method, reference, date)', 'State the status: unpaid, partially_paid, paid or overdue', 'Issue or verify the receipt; communicate any remaining due with where to pay'],
                'example' => '[TRAINING] £1,000 service: £400 received → Paid £400, Due £600, partially_paid. Final £600 → Paid £1,000, Due £0, PAID. Each step references its payment record.',
                'expected' => 'Every money statement traceable to a record; customers always know exactly what is due.',
                'mistakes' => ['Marking unpaid invoices as paid', 'Confirming on a phone promise', 'Ignoring partial balances', 'Duplicate income entries'],
                'problems' => ['payment-not-showing', 'balance-wrong', 'invoice-problem'],
            ],
            [
                'slug' => 'projects', 'category' => 'delivery', 'title' => 'Project Management',
                'summary' => 'Confirmed orders become projects with milestones, teams, dates and status.',
                'what' => 'Projects (project tier: Admin → Projects) are the customer-visible delivery containers: name (customer + service), linked customer and service, start and expected completion, project manager, team, milestones and status. Projects trace to confirmed orders — never free-floating.',
                'why' => 'Unlinked projects break finance traceability and customer visibility.',
                'who' => 'Project managers create and steer; teams execute; customers track progress.',
                'when' => 'Immediately after order confirmation; milestones defined before work starts.',
                'steps' => ['Create from the confirmed order with correct customer linkage', 'Set dates, manager and team', 'Define milestones mirroring the proposal', 'Set status and notify the customer of the plan'],
                'example' => '[TRAINING] [TRAINING] NorthBridge — Website Security Assessment: milestones Assessment → Analysis → Report → Review → Delivery, 3-week window, PM plus two specialists.',
                'expected' => 'A dated, owned, milestone-driven plan the customer can follow.',
                'mistakes' => ['Projects with no milestones or dates', 'Wrong customer linked', 'Starting before confirmation'],
                'problems' => ['project-not-created', 'progress-not-updating', 'cannot-complete-project'],
            ],
            [
                'slug' => 'tasks', 'category' => 'delivery', 'title' => 'Task Management',
                'summary' => 'Assign, prioritize, track, verify and close tasks with evidence.',
                'what' => 'Tasks (Admin → Tasks) are the internal work units inside projects: title, assignee, priority, deadline, status flow, notes, attachments and dependencies. Completion requires independent verification.',
                'why' => 'Tasks are where SLAs and quality live or die. Unverified “done” is how defects reach customers.',
                'who' => 'Assignees execute; reviewers approve or reject; PMs watch dependencies.',
                'when' => 'Created at project setup; updated continuously; verified at completion.',
                'steps' => ['Create with assignee, priority and deadline', 'Record dependencies (analysis waits for testing)', 'Work with notes and attached evidence', 'Submit for verification; reviewer approves or rejects with reasons'],
                'example' => '[TRAINING] Assessment tasks: Requirement Review → Authorized Testing → Findings Analysis → Report → Quality Review → Customer Delivery. Task 2 closes only with scoped test evidence attached.',
                'expected' => 'Every task owned, dated, evidenced and verified.',
                'mistakes' => ['Closing before verification', 'Testing outside authorized scope', 'Missing dependencies causing stalls'],
                'problems' => ['cannot-access-task', 'progress-not-updating'],
            ],
            [
                'slug' => 'it-services', 'category' => 'delivery', 'title' => 'IT Service Delivery',
                'summary' => 'Support, authorized cybersecurity, web development and marketing delivery patterns.',
                'what' => 'Delivery pattern per line: IT support (Windows, Microsoft 365, email, network, server, backup, remote, hardware/software), cybersecurity (assessments, authorized testing, config review, reporting, remediation guidance), web development (build, maintain, fix, deploy) and digital marketing (SEO, analytics, content, campaigns). All follow request → scope → quote → approval → order → payment → project → tasks → work → update → review → completion.',
                'why' => 'Undocumented changes are indistinguishable from incidents; out-of-scope testing IS a security incident.',
                'who' => 'Assigned specialists deliver; PMs coordinate; customers confirm outcomes.',
                'when' => 'Only inside written scope with backups and rollback considered first.',
                'steps' => ['Confirm scope, access and backup state in writing', 'Execute per task with notes and attachments', 'Quality-check against the requirement', 'Update the customer and get confirmation'],
                'example' => '[TRAINING] Microsoft 365 mailbox migration: scope (25 mailboxes, weekend window), backup verified, per-batch notes, customer confirms mail flow Monday.',
                'expected' => 'Scoped, evidenced, confirmed delivery — no surprises.',
                'mistakes' => ['Scope creep without quotation', 'No rollback plan', 'Extra “helpful” testing outside authorization'],
                'problems' => ['windows-issue', 'm365-issue', 'network-issue'],
            ],
            [
                'slug' => 'tickets', 'category' => 'delivery', 'title' => 'Tickets & Customer Support',
                'summary' => 'Ticket lifecycle: categorize, prioritize, assign, investigate, respond, resolve, confirm, close.',
                'what' => 'Tickets (customers: /portal/tickets; staff support hierarchy: Admin → Tickets) are customer issues with category, priority, assignee, messages, internal notes, status and full history. Flow: received → categorized → prioritized → assigned → investigated → responded → resolved → customer confirms → closed (reopenable).',
                'why' => 'Tickets are timestamped promises. Wrong triage hides work from specialists; silent tickets destroy trust.',
                'who' => 'Support hierarchy owns tickets end to end; specialists are pulled in by category.',
                'when' => 'Triage immediately on arrival; respond inside the response SLA.',
                'steps' => ['Categorize the area and prioritize by impact × urgency', 'Assign an owner immediately', 'Respond inside SLA with a plan, not just acknowledgement', 'Investigate, resolve, then request customer confirmation', 'Close; reopen on recurrence with linked history'],
                'example' => '[TRAINING] “Email down for 5 users” → category Email, priority High, owner assigned in 10 minutes, workaround in 1 hour, fix verified by the customer, closed with root cause noted.',
                'expected' => 'Every ticket owned, timestamped, confirmed and traceable.',
                'mistakes' => ['Wrong category routing work to the wrong team', 'Closing without confirmation', 'Internal notes posted publicly'],
                'problems' => ['ticket-not-assigned', 'customer-cannot-see-response', 'sla-at-risk'],
            ],
            [
                'slug' => 'sla', 'category' => 'delivery', 'title' => 'SLA Management',
                'summary' => 'Response vs resolution clocks, breach prevention, escalation and communication.',
                'what' => 'SLA policies define response time (first human reply) and resolution time (fix delivered) per priority, with deadlines, escalation paths and breach consequences. Overdue tickets need a plan and an owner.',
                'why' => 'SLA is contractual. Breaches cost credits, renewals and reputation.',
                'who' => 'Ticket owners watch their clocks; leads watch the queue; managers own breaches.',
                'when' => 'Continuously — warn the customer BEFORE a deadline, never after.',
                'steps' => ['Know the two clocks on every ticket you own', 'Work the queue in deadline order', 'Warn early with cause, impact, new time and owner', 'On breach: escalate, remediate, document, learn'],
                'example' => '[TRAINING] High-priority response SLA 1h, resolution 8h. At 45 minutes with no fix, the owner posts: cause found, workaround live, fix ETA 3h — breach avoided, trust kept.',
                'expected' => 'Zero silent breaches; every at-risk ticket has a visible plan.',
                'mistakes' => ['Confusing response with resolution', 'Silent breaches', 'No owner on overdue tickets'],
                'problems' => ['sla-at-risk', 'ticket-not-assigned'],
            ],
            [
                'slug' => 'progress-updates', 'category' => 'delivery', 'title' => 'Work Progress Updates',
                'summary' => 'Customer-visible updates vs internal notes: percentages with evidence, next steps, dates.',
                'what' => 'Progress updates (project comments/updates) tell customers state, evidence, next step and next date. Internal notes hold planning, assignments and debate — staff only. Percentages must reflect milestone evidence, not optimism.',
                'why' => 'Updates are the product until delivery. One leaked internal note can breach confidentiality or panic a customer.',
                'who' => 'Task owners draft; PMs ensure rhythm; everyone double-checks the channel.',
                'when' => 'At every milestone movement and on every promised date — met or slipped.',
                'steps' => ['Confirm actual stage and evidence', 'Set percentage against milestones', 'State next step and next update date', 'Attach appropriate files; check channel; notify'],
                'example' => '[TRAINING] Website Security Assessment, Analysis, 60%: “Initial assessment completed. The team is now reviewing findings and preparing the technical report. Next step: technical review. Next update: tomorrow.”',
                'expected' => 'Customers never have to ask “what is happening?” — and never see internals.',
                'mistakes' => ['“90%” for weeks', 'Updates with no next date', 'Raw findings pasted unreviewed'],
                'problems' => ['customer-update-not-visible', 'progress-not-updating'],
            ],
            [
                'slug' => 'invoices', 'category' => 'finance', 'title' => 'Invoices & Receipts',
                'summary' => 'Invoice lifecycle draft → sent → paid/partial/overdue; receipts and the paid checklist.',
                'what' => 'Invoices (finance tier: Admin → Invoices) demand money: line items, subtotal, tax rate and amount, total, amount_paid, amount_due, status (draft, sent, partially_paid, paid, overdue, cancelled), due date and PDF. Receipts prove each payment.',
                'why' => 'False “paid” statements create legal and trust exposure. Records are the only truth.',
                'who' => 'Finance tier creates and verifies; delivery checks status before milestones and closure.',
                'when' => 'Issue after acceptance/terms trigger; verify before every money statement.',
                'steps' => ['Read subtotal, tax, total, paid and due', 'List all payment records with references', 'Confirm due is £0 and history is clean before saying “paid”', 'Send receipt or invoice; state any balance with where to pay'],
                'example' => '[TRAINING] £550 invoice, £0 paid, past due → overdue. After verified £550 receipt → paid, receipt sent, closure gate unlocked.',
                'expected' => 'Every invoice state provable from records in under a minute.',
                'mistakes' => ['Confirming paid from memory', 'Skipping transaction history', 'Confusing overdue with cancelled'],
                'problems' => ['invoice-problem', 'balance-wrong', 'payment-not-showing'],
            ],
            [
                'slug' => 'finance', 'category' => 'finance', 'title' => 'Finance Overview',
                'summary' => 'How money moves: payments → income → expenses → profit, with reports and reconciliation.',
                'what' => 'Finance (finance tier: Financials, Transactions, Reports) tracks income (completed customer receipts), expenses (categorized, documented, approved), outstanding balances, commissions, refunds and profit/loss. Revenue − Expenses = Profit, computed from completed records.',
                'why' => 'Miscategorized or duplicated entries corrupt tax, payroll and every management report.',
                'who' => 'Finance tier owns records; delivery provides evidence; admins oversee.',
                'when' => 'At every receipt, every spend, every reconciliation and every closure.',
                'steps' => ['Record income once, against a payment reference', 'Create expenses with category, date, vendor and proof; get approval', 'Reconcile: payments equal income per invoice; balances explain the rest', 'Read P&L and reports only from completed records'],
                'example' => '[TRAINING] Month: completed income £8,000, approved expenses £2,500 → profit £5,000. One £400 receipt appears exactly once, tied to its reference.',
                'expected' => 'Reconciled books where every number has a reference.',
                'mistakes' => ['Duplicate income', 'Counting pending as received', 'Uncategorized expenses'],
                'problems' => ['income-missing', 'profit-mismatch', 'duplicate-transaction'],
            ],
            [
                'slug' => 'income-expenses', 'category' => 'finance', 'title' => 'Income & Expense Recording',
                'summary' => 'When income counts, how expenses are documented and approved.',
                'what' => 'Income counts when payment evidence exists (completed records). Expenses need category (e.g. Infrastructure), date, amount, vendor, description and supporting documentation, then approval where required.',
                'why' => 'Duplicates inflate revenue and tax exposure; undocumented spend cannot be defended.',
                'who' => 'Finance tier records; spenders attach proof; approvers clear.',
                'when' => 'Income at each verified receipt; expenses at spend time, not month-end.',
                'steps' => ['Match each receipt to invoice plus reference; record once', 'Create each expense complete with proof', 'Submit for approval; correct rejections fast', 'Reconcile totals per invoice and per period'],
                'example' => '[TRAINING] £120 monthly hosting: category Infrastructure, vendor, invoice PDF attached, approved — visible in hosting cost reports ever after.',
                'expected' => 'Complete, approved, reconcilable money records.',
                'mistakes' => ['Month-end expense dumps', 'Missing receipts', 'Recording before evidence'],
                'problems' => ['income-missing', 'expense-missing'],
            ],
            [
                'slug' => 'commission', 'category' => 'finance', 'title' => 'Commission Management',
                'summary' => 'Eligibility on paid sales, rule rates, approve/reject, payouts — and the five-way money split.',
                'what' => 'Commissions (finance tier) reward qualifying, PAID sales per commission rules. Keep apart: Customer Payment (cash in) → Company Revenue (recognized income) → Employee Commission (a company expense) → Company Expenses → Company Profit (what remains).',
                'why' => 'Commission is both payroll fairness and a cost line. Errors overpay or underpay people.',
                'who' => 'Agents earn; finance tier reviews, approves or rejects with reasons, and batches payouts.',
                'when' => 'After the underlying sale is paid and qualifying — never before.',
                'steps' => ['Confirm the sale is paid and qualifying under the rule', 'Apply the rate; approve or reject with evidence', 'Include approved items in payout batches'],
                'example' => '[TRAINING] £1,500 paid order × 5% rule = £75 commission, approved after payment evidence, batched in the monthly payout.',
                'expected' => 'Every payout traceable to a paid sale and a rule.',
                'mistakes' => ['Commission on unpaid or cancelled sales', 'Confusing revenue with profit'],
                'problems' => ['income-missing', 'profit-mismatch'],
            ],
            [
                'slug' => 'profit-loss', 'category' => 'finance', 'title' => 'Profit & Loss',
                'summary' => 'Reading P&L the way the platform computes it: completed income minus completed expenses.',
                'what' => 'Profit/loss reports sum completed income and approved/completed expenses. Your job is correct categorization and documentation — never invented formulas.',
                'why' => 'Management prices, hires and invests off P&L. Garbage in, catastrophe out.',
                'who' => 'Finance tier prepares; managers and admins read and act.',
                'when' => 'Period closes, pricing reviews, and before big commitments.',
                'steps' => ['Ensure all income is evidenced and all expenses approved', 'Read revenue, expenses and profit lines separately', 'Drill into anomalies before reporting conclusions'],
                'example' => '[TRAINING] Revenue £5,000 − Expenses £1,500 = Profit £3,500. A £1,200 hosting line under Software would mislead infrastructure decisions — categorization matters.',
                'expected' => 'P&L you can defend line by line.',
                'mistakes' => ['Reporting pending as profit', 'Ignoring miscategorization'],
                'problems' => ['profit-mismatch', 'duplicate-transaction'],
            ],
            [
                'slug' => 'account-closure', 'category' => 'finance', 'title' => 'Account Closure',
                'summary' => 'Task done ≠ account closed. Verify delivery, money, documents and notifications in order.',
                'what' => 'Closure gate: tasks completed and verified → quality checked → deliverables provided → customer notified → final invoice checked → final payment confirmed → due £0 → refunds/adjustments cleared → project completed → financial status closed → follow-up scheduled.',
                'why' => 'Premature closure hides debt and breaks reports. Money verification is a separate gate from work verification.',
                'who' => 'Delivery verifies work; finance verifies money; PM owns the gate.',
                'when' => 'Only when every gate is evidenced — never on “task completed” alone.',
                'steps' => ['Verify all tasks, quality and deliverables', 'Confirm final invoice and £0 due with finance', 'Close project and financial status', 'Notify the customer; schedule follow-up'],
                'example' => '[TRAINING] NorthBridge £1,500 paid in full: task evidence filed, quality note signed, invoice paid, £0-due proof attached, closure notice sent, follow-up in 30 days.',
                'expected' => 'Closed accounts with zero balance, filed proof and a next contact date.',
                'mistakes' => ['Closing with open tasks or balances', 'No follow-up scheduled'],
                'problems' => ['cannot-complete-project', 'balance-wrong'],
            ],
            [
                'slug' => 'knowledge-base', 'category' => 'knowledge', 'title' => 'Knowledge Base',
                'summary' => 'Searching, reading, authoring and visibility: internal vs customer-facing knowledge.',
                'what' => 'The KB (public articles; Admin → Knowledge Base for authoring) holds approved know-how with categories, difficulty and public/internal visibility. Lessons link to articles instead of duplicating them.',
                'why' => 'One maintained answer beats ten stale copies. Wrong visibility leaks internals or starves customers.',
                'who' => 'Everyone searches first; authorized authors create and update; admins approve publishing.',
                'when' => 'Before asking, before answering customers, and whenever you spot outdated content.',
                'steps' => ['Search before creating or asking', 'Use the approved article; follow it exactly', 'Update what you own; flag the rest with specifics', 'Set visibility deliberately on every edit'],
                'example' => '[TRAINING] “How to create a support ticket” (public, beginner) is linked from onboarding lessons instead of rewritten in five places.',
                'expected' => 'Fresh, single-source, correctly-visible knowledge.',
                'mistakes' => ['Duplicating articles instead of linking', 'Internal notes marked public', 'Stale articles left to mislead'],
                'problems' => ['missing-content', 'customer-update-not-visible'],
            ],
            [
                'slug' => 'ai-assistant', 'category' => 'knowledge', 'title' => 'AI Customer Assistant',
                'summary' => 'What the AI answers, its KB sources, escalation, and what it must never invent.',
                'what' => 'The AI assistant answers from approved KB sources, escalates uncertainty to humans, and requires identity verification for account-specific answers. It must never invent policies, prices, payment states or customer facts.',
                'why' => 'AI confidence is not evidence. A hallucinated balance or policy becomes your liability once sent.',
                'who' => 'Customers chat; employees review AI-drafted content before it reaches customers; admins tune sources.',
                'when' => 'Use for approved information lookup; escalate identity, money and dispute topics to humans.',
                'steps' => ['Let AI handle approved, sourced questions', 'Verify AI drafts before sending to customers', 'Escalate payment, identity and complaint topics to humans', 'Feed corrections back into KB articles'],
                'example' => '[TRAINING] AI correctly quotes ticket-creation steps from the KB — but a “what is my balance?” question is verified against records by a human first.',
                'expected' => 'Fast answers with zero invented facts reaching customers.',
                'mistakes' => ['Pasting AI output unverified', 'Letting AI state balances or policies'],
                'problems' => ['customer-cannot-see-response', 'email-not-sent'],
            ],
            [
                'slug' => 'website-updates', 'category' => 'knowledge', 'title' => 'Website Content Updates',
                'summary' => 'Draft → review → approve → publish → verify, with a pre-publish checklist.',
                'what' => 'Authorized staff publish news, service updates, portfolio, case studies and knowledge articles (Admin → Blog, Content, Knowledge Base). Every publication follows draft → review → approval → publish → verify-the-public-page.',
                'why' => 'Public errors price directly into trust: wrong prices, broken links and leaked names.',
                'who' => 'Authors draft; reviewers check; admins approve; authors verify live.',
                'when' => 'Never publish unapproved content, however urgent it feels.',
                'steps' => ['Draft with sources and synthetic-only examples', 'Peer review plus approval', 'Publish, then verify live: spelling, pricing, images, links, dates, confidentiality, SEO, mobile'],
                'example' => '[TRAINING] Case study “[TRAINING] Secure Website Assessment”: challenge, authorized work, report result, completed — no customer names, verified on mobile before sign-off.',
                'expected' => 'Live pages you would show any customer with pride.',
                'mistakes' => ['Skipping approval', 'Real customer names published', 'Untested mobile layout'],
                'problems' => ['missing-content', 'broken-link', 'page-not-loading'],
            ],
            [
                'slug' => 'security', 'category' => 'security', 'title' => 'Security & Data Protection',
                'summary' => 'Least privilege, MFA, confidentiality, phishing awareness and safe handling.',
                'what' => 'Everyday operational security: least-privilege access, unique passwords plus MFA (authenticator app preferred), minimum-necessary customer data, secure document handling by classification, phishing verification and fast anomaly reporting. Security testing only inside written, agreed scope.',
                'why' => 'Most breaches start with routine mistakes. Audit logs record access actions — act accordingly.',
                'who' => 'Everyone, every day; specialists additionally bound by testing authorization.',
                'when' => 'Before clicking, before sharing, before uploading — always.',
                'steps' => ['Enable MFA; use unique passwords', 'Handle documents by classification; never train on real data', 'Verify senders and links; report phishing', 'Report suspicious activity immediately with facts'],
                'example' => '[TRAINING] A “CEO” email demands an urgent transfer. Employee verifies via a known channel — spoofed domain confirmed — reports it instead of paying.',
                'expected' => 'Quiet, uneventful security posture built from habits.',
                'mistakes' => ['Real data in training', 'Password reuse', 'Out-of-scope “helpful” testing'],
                'problems' => ['cannot-login', 'page-not-loading'],
            ],
        ];
    }

    public static function find(string $slug): ?array
    {
        foreach (self::all() as $lesson) {
            if ($lesson['slug'] === $slug) {
                return $lesson;
            }
        }

        return null;
    }

    public static function orderedSlugs(): array
    {
        return array_column(self::all(), 'slug');
    }
}
